name: pipeline

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run clean
      - run: npm run lint
      - run: npm run build
      - run: npm test
        env:
          CI: true
      - run: npm run e2e
        env:
          CI: true

      - uses: actions/upload-artifact@v2
        if: matrix.node-version == '14.x'
        with:
          name: dist
          path: |
            projects/*/bin
            projects/*/dist
            projects/*/index.js
            projects/*/package.json

  automerge:
    name: Auto-merge dependency updates
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
      - name: Merge
        uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.createReview({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                event: 'APPROVE'
            })
            github.pullRequests.merge({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}

  deploy-pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [ build ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: projects
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: projects/todo-app-ui/dist
